codecov:
  branch: main
  disable_default_path_fixes: true
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
fixes:
  - "main/::"
